name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t rmeiradev/php7.4-alpine-fpm-nginx . && docker push rmeiradev/php7.4-alpine-fpm-nginx
